# ATTENTION: la source de ce fichier ce trouve dans le répertoire "Target"

# nom des blocs "system"
PARAM_NAME_BLOC_DT = "dt"
PARAM_NAME_BLOC_OUTPUT = "output"
PARAM_NAME_BLOC_INPUT = "input"
PARAM_NAME_BLOC_PREVIOUS = "previous"
PARAM_NAME_BLOC_SELECT = "select"
PARAM_NAME_BLOC_VALIDREAD = "validRead"
PARAM_NAME_BLOC_VALIDWRITE = "validWrite"
PARAM_NAME_BLOC_MINMAX = "minmax"
PARAM_NAME_BLOC_COMP = "comp"
PARAM_NAME_BLOC_AND = "and"
PARAM_NAME_BLOC_OR = "or"
PARAM_NAME_BLOC_NOT = "not"
PARAM_NAME_BLOC_EDGE = "edge"
PARAM_NAME_BLOC_ADD = "add"
PARAM_NAME_BLOC_SUB = "sub"
PARAM_NAME_BLOC_MULT = "mult"
PARAM_NAME_BLOC_DIV = "div"
PARAM_NAME_BLOC_CABLIN = "cablin"
PARAM_NAME_BLOC_CABLOUT = "cablout"
PARAM_NAME_BLOC_CONST_PI = "const.pi"

