# ATTENTION: la source de ce fichier ce trouve dans le répertoire "Target"

PARAM_VAL_INIT_INPUT= 555
PARAM_VAL_INIT_OUTPUT= 666
PARAM_CHEMIN_SYSTEM = "blocs/system/"
PARAM_CHEMIN_USER = "blocs/user/"

#PARAM_COLOR_CANVAS_BG_DEFAUT = "ivory"
PARAM_COLOR_CANVAS_BG_MAIN = "beige"
PARAM_COLOR_CANVAS_BG_SECOND = "honeydew1"
#PARAM_COLOR_CANVAS_BG_MONITORING = "#AFEEEE"
PARAM_COLOR_CANVAS_BG_MONITORING = "mistyrose"
#PARAM_COLOR_CANVAS_BG_MONITORING = "thistle"
#PARAM_COLOR_CANVAS_BG_MONITORING = "lavenderblush"
PARAM_COLOR_BG_HEADER_USER = "white"
PARAM_COLOR_BG_HEADER_SYSTEM = "snow3"
PARAM_COLOR_BG_HEADER_INPUT = "orange"
PARAM_COLOR_BG_HEADER_OUTPUT = "lime green"
PARAM_COLOR_BG_IO_FORCED_VALIDE =  "yellow"
PARAM_COLOR_BG_IO_FORCED_INVALIDE =  "black"
PARAM_COLOR_BG_IO_INVALIDE =  "#FF0000"
PARAM_COLOR_BG_IO_VALIDE  =  "#00FF00"
PARAM_COLOR_TX_IO_BLACK =  "#000000"
PARAM_COLOR_TX_IO_WHITE  =  "#FFFFFF"
PARAM_COLOR_BG_INPUT =  "burlywood1"
PARAM_COLOR_BG_OUTPUT = "DarkSeaGreen1"
PARAM_COLOR_BG_MEMORY = "greenyellow"

PARAM_COLOR_LINK_MODULO = 4
PARAM_COLOR_LINK_STANDARD = ["#800080", "#A00000", "#0000A0", "#00A000"]
PARAM_COLOR_LINK_LOOP = "greenyellow"
PARAM_COLOR_LINK_BREAK = "#FF8080"
#PARAM_BLACK_COLOR = "#000000"
PARAM_COLOR_MENU_TEXTE_DANGER = "#FF1507"
PARAM_COLOR_MENU_TEXTE_WARNING = "#A52A2A"
PARAM_COLOR_MENU_TEXTE_SELECTED = "#105510"
PARAM_COLOR_MENU_TEXTE_NORMAL = "#000000"
#PARAM_INVALID_MENU_TEXT_COLOR = "#AAAAAA"
PARAM_MONITORING_FLOAT_NB_DIGIT = 10

PARAM_ICONE_DISQUETTE = "💾"
PARAM_ICONE_OEIL = "👁️"
PARAM_ICONE_INITIALISATION = "🔄"
PARAM_ICONE_EVENT = "⚡"
#PARAM_FLECHE_DROITE = "►"
#PARAM_FLECHE_DROITE = "■"
#PARAM_FLECHE_DROITE = "▌"
#PARAM_FLECHE_DROITE = "〓"
#PARAM_FLECHE_DROITE = "◆"
#PARAM_FLECHE_DROITE = "→"
#PARAM_FLECHE_DROITE = "⇒"
#PARAM_FLECHE_DROITE = "⟶"
PARAM_FLECHE_DROITE = "➔"
PARAM_DEFAUT_THREAD_ID = 2

PARAM_RATIO_FENETRE_A_LOUVERTURE = 1.5
PARAM_ROUTAGE_DX = 550
PARAM_ROUTAGE_MARGE_DY = 20
PARAM_ROUTAGE_HEADER_DY = 50
PARAM_ROUTAGE_IO_DY = 50
PARAM_ROUTAGE_PREVIOUS_DY = 200
PARAM_ROUTAGE_OUTPUT_DY = 100
#PARAM_ROUTAGE_PREVIOUS_ON_TOP = False
PARAM_LIEN_MARGE_X = 36 #18
PARAM_LIEN_BACKLOOP_Y = 180 #100
PARAM_LIEN_ZIGZAG = 8
PARAM_LIEN_LENGTH_X = PARAM_ROUTAGE_DX
PARAM_LIEN_WIDTH = 3

PARAM_ZOOM_DEFAUT = 0.5
PARAM_ZOOM_INCREMENT = 1.25
PARAM_NEAR = 5
PARAM_FONT = "Helvitica"
PARAM_FONT_SIZE = 25
PARAM_HEADER_HAUTEUR = 50
PARAM_HEADER_LARGEUR = 380 #420

PARAM_TYPE_LIST = ["int", "float", "bool", "str"]

PARAM_COMPIL_ERROR_FUNCTION_NOT_DEFINED_FOR_THIS_BLOC = 1
PARAM_COMPIL_ERROR_OUT_NOT_FOUND_IN_USER_BLOC = 2
PARAM_COMPIL_ERROR_INPUT_BLOC_WITH_LINK = 3



